# file: site.yml
---
- hosts: all
  become: yes
  vars:
    certbot_auto_renew: true
    certbot_auto_renew_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
    certbot_auto_renew_minute: 20
    certbot_auto_renew_hour: 5
    certbot_auto_renew_options: "--quiet --no-self-upgrade"
    certbot_certs:
      - email: 'andrewcr330@gmail.com'
        domains:
          - crowley.cloud
    certbot_create_standalone_stop_services:
      - nginx
  roles:
    - crowley.cloud
    - geerlingguy.certbot