# file: site.yml
---
- hosts: all
  become: yes
  vars:
    certbot_admin_email: andrewcr330@gmail.com
    certbot_create_if_missing: true
    certbot_certs:
      - domains:
          - crowley.cloud
    nginx_vhosts:
      - listen: "443 ssl http2"
        server_name: "certbot-test.servercheck.in"
        root: "/var/www/html/crowley.cloud/html"
        index: "index.html index.htm"
        state: "present"
        template: "{{ nginx_vhost_template }}"
        filename: "certbot_test.conf"
        extra_parameters: |
          ssl_certificate     /etc/letsencrypt/live/certbot-test.servercheck.in/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/certbot-test.servercheck.in/privkey.pem;
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;
    certbot_create_standalone_stop_services:
      - nginx
  roles:
    - crowley.cloud
    - geerlingguy.certbot