# file: site.yml
---
- hosts: all
  become: yes
  vars:
    certbot_auto_renew_user: your_username_here
    certbot_auto_renew_minute: 20
    certbot_auto_renew_hour: 5
    certbot_certs:
      - email: 'andrewcr330@gmail.com'
        domains:
          - crowley.cloud
  roles:
    - roles/crowley.cloud
