# file: site.yml
---
- hosts: all
  become: yes
  vars:
    certbot_auto_renew: true
    certbot_auto_renew_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
    certbot_auto_renew_hour: 3
    certbot_auto_renew_minute: 30
    certbot_auto_renew_options: "--quiet --no-self-upgrade"
    certbot_certs:
    - email: andrewcr330@gmail.com
      domains:
      - "{{DOMAIN}}"
  roles:
    - roles/crowley.cloud
