# file: site.yml
---
- hosts: all
  become: yes
  roles:
    - roles/geerlingguy.repo-epel
    - roles/geerlingguy.pip
    - roles/crowley.cloud
  tasks:
    - name: Flush handlers in case any configs have changed.
      meta: flush_handlers
