# file: site.yml
---
- hosts: all
  become: yes
  vars:
    domain_name: crowley.cloud
    letsencrypt_email: andrewcr330@gmail.com
    certbot_nginx_cert_name: crowleycloudcert
  roles:
    - roles/crowley.cloud
