# file: site.yml
---
- hosts: all
  become: yes
  vars:
    certbot_create_if_missing: true
    certbot_create_method: standalone
    certbot_auto_renew: true
    certbot_auto_renew_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
    certbot_auto_renew_minute: 20
    certbot_auto_renew_hour: 5
    certbot_certs:
      - email: 'andrewcr330@gmail.com'
        domains:
          - crowley.cloud
    certbot_create_standalone_stop_services:
      - nginx
    nginx_service_state: stopped
    nginx_service_enabled: yes
    nginx_vhosts:
      - listen: "443 ssl http2"
        server_name: "crowley.cloud"
        root: "{{ crowley_cloud_html_dir }}"
        index: "index.html index.htm"
        state: "present"
        template: "{{ nginx_vhost_template }}"
        filename: "crowley_cloud.conf"
        extra_parameters: |
          ssl_certificate     /etc/letsencrypt/live/crowley.cloud/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/crowley.cloud/privkey.pem;
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;
  roles:
    - geerlingguy.repo-epel
    - geerlingguy.pip
    - geerlingguy.certbot
    - geerlingguy.nginx
    - roles/crowley.cloud