# file: roles/crowley.cloud/tasks/main.yml
---
- name: Install packages(git,curl)
  package:
    name: ['curl', 'git', 'awscli', 'vim']
    state: present
- name: Install boto for s3 sync
  pip:
    name: boto
  notify:
    - stop nginx
- name: create crowley.cloud html directory
  file:
    path: "{{crowley_cloud_html_dir}}"
    state: directory
    owner: nginx
    group: nginx
- name: install nginx
  import_role:
    name: nginxinc.nginx
  vars:
    nginx_vhosts:
      - listen: "443 ssl http2"
        server_name: "certbot-test.servercheck.in"
        root: "{{crowley_cloud_html_dir}}"
        index: "index index.html index.htm"
        state: "present"
        template: "{{ nginx_vhost_template }}"
        filename: "certbot_test.conf"
        extra_parameters: |
          ssl_certificate     /etc/letsencrypt/live/certbot-test.servercheck.in/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/certbot-test.servercheck.in/privkey.pem;
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;
- name: add healthcheck.html
  template:
    src: templates/healthcheck.html.j2
    dest: "{{crowley_cloud_html_dir}}/healthcheck.html"
    owner: nginx
    group: nginx
    mode: 0644
- name: get that cv
  import_tasks: 'cv.yml'
- name: get certbot working
  import_role:
    name: geerlingguy.certbot
  vars:
    certbot_admin_email: andrewcr330@gmail.com
    certbot_create_if_missing: true
    certbot_certs:
      - domains:
          - crowley.cloud
    certbot_create_standalone_stop_services:
      - nginx