---
- name: move web to server
  synchronize: 
    dest: "{{crowley_cloud_html_dir}}"
    src: files/www/
    compress: no
- name: create crowley.cloud html directory
  file:
    path: "{{crowley_cloud_html_dir}}"
    state: directory
    owner: nginx
    group: nginx
    recurse: yes