---
- name: move web to server
  synchronize: 
    dest: "{{crowley_cloud_html_dir}}"
    src: files/www/
    compress: no
- name: check permissions
  file:
    path: "{{crowley_cloud_html_dir}}"
    state: directory
    owner: nginx
    group: nginx
    mode: 0775
    recurse: yes
- name: nginx started
  service:
    name: nginx
    state: started