---
- name: move web to server
  synchronize:
    dest: /var/www/html/crowley.cloud/html/
    src: files/www/
- name: create crowley.cloud html directory
  file:
    path: "{{crowley_cloud_html_dir}}"
    state: directory
    owner: nginx
    group: nginxa
    recurse: yes