---
- name: Add conf
  template:
    src: templates/crowley.cloud.conf.j2
    dest: "/etc/ngin/conf.d/crowley.cloud.conf"
    owner: nginx
    group: nginx
    mode: 0644
- name: Create cron for s3 pull
  cron:
    name: Pull from s3
    job: aws s3 sync s3://crowley.cloud/* "{{crowley_cloud_html_dir}}" --recursive   
    minute: 1/10