---
# - name: Add conf
#   template:
#     src: templates/crowley.cloud.conf.j2
#     dest: "/etc/nginx/conf.d/crowley.cloud.conf"
#     owner: nginx
#     group: nginx
#     mode: 0644
- name: move web to server
  copy:
      dest: /var/www/html/crowley.cloud/html/
      src: files/www/