# file: roles/crowley.cloud/tasks/main.yml
---
- name: import nginx
  import_role:
    name: geerlingguy.nginx
  vars:
    nginx_service_state: stopped
    nginx_service_enabled: yes
    nginx_vhosts:
      - listen: "443 ssl http2"
        server_name: "crowley.cloud"
        root: "{{ crowley_cloud_html_dir }}"
        index: "index.html index.htm"
        state: "present"
        template: "{{ nginx_vhost_template }}"
        filename: "crowley_cloud.conf"
        extra_parameters: |
          ssl_certificate     /etc/letsencrypt/live/crowley.cloud/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/crowley.cloud/privkey.pem;
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;
- name: import certbot
  import_role:
    name: geerlingguy.certbot
  vars:
    certbot_create_standalone_stop_services:
      - nginx
    certbot_create_if_missing: true
    certbot_create_method: standalone
    certbot_auto_renew: true
    certbot_auto_renew_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
    certbot_auto_renew_minute: 20
    certbot_auto_renew_hour: 5
    certbot_certs:
      - email: 'andrewcr330@gmail.com'
        domains:
          - crowley.cloud
- name: Install packages(git,curl)
  package:
    name: ['curl', 'git', 'awscli', 'vim']
    state: present
- name: Install boto for s3 sync
  pip:
    name: boto
- name: create crowley.cloud html directory
  file:
    path: "{{crowley_cloud_html_dir}}"
    state: directory
    owner: nginx
    group: nginx
- name: add healthcheck.html
  template:
    src: templates/healthcheck.html.j2
    dest: "{{crowley_cloud_html_dir}}/healthcheck.html"
    owner: nginx
    group: nginx
    mode: 0644
- name: get that cv
  import_tasks: 'cv.yml'