# file: roles/crowley.cloud/tasks/main.yml
---
- name: Install packages(git,curl)
  yum:
    name: ['curl', 'git', 'awscli', 'vim']
    state: present
    lock_timeout: 180
- name: import nginx
  import_role:
    name: geerlingguy.nginx
  vars:
    nginx_service_state: started
    nginx_service_enabled: yes
- name: Install boto for s3 sync
  pip:
    name: boto
- name: create crowley.cloud html directory
  file:
    path: "{{crowley_cloud_html_dir}}"
    state: directory
    owner: nginx
    group: nginx
- name: add healthcheck.html
  template:
    src: templates/healthcheck.html.j2
    dest: "{{crowley_cloud_html_dir}}/healthcheck.html"
    owner: nginx
    group: nginx
    mode: 0644
- name: get that cv
  import_tasks: 'cv.yml'