# file: roles/crowley.cloud/tasks/main.yml
---
- name: Install packages(git,curl)
  apt: name={{item}} state=present
  with_items:
    - curl
    - git
- name: create crowley.cloud html directory
  file:
    path: "{{crowley_cloud_html_dir}}"
    state: directory
    owner: "{{nginx_user}}"
    group: www-data
- import_tasks: cv.yml
- name: add healthcheck.html
  template:
    src: templates/healthcheck.html.j2
    dest: "{{crowley_cloud_html_dir}}/healthcheck.html "
    owner: "{{nginx_user}}"
    group: www-data
    mode: 0644
