# file: roles/crowley.cloud/handlers/main.yml
---
# For example,
#
- name: restart nginx
  service:
    name: nginx
    state: restarted
- name: stop nginx
  service:
    name: nginx
    state: stopped